//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bootstrap.Themes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bootstrap.Themes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&apos;//fonts.googleapis.com/css?family=Lobster|Cabin:400,700&apos;);/*!
        /// * Bootstrap v2.3.2
        /// *
        /// * Copyright 2013 Twitter, Inc
        /// * Licensed under the Apache License v2.0
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Designed and built with all the love in the world by @mdo and @fat.
        /// */.clearfix{*zoom:1}.clearfix:before,.clearfix:after{display:table;line-height:0;content:&quot;&quot;}.clearfix:after{clear:both}.hide-text{font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}.input [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string amelia_bootstrap_min {
            get {
                return ResourceManager.GetString("amelia_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2017 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcapt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cerulean_bootstrap_min {
            get {
                return ResourceManager.GetString("cerulean_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2017 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cosmo_bootstrap_min {
            get {
                return ResourceManager.GetString("cosmo_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Roboto:400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cyborg_bootstrap_min {
            get {
                return ResourceManager.GetString("cyborg_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Lato:400,700,400italic&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string darkly_bootstrap_min {
            get {
                return ResourceManager.GetString("darkly_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Lato:400,700,400italic&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flatly_bootstrap_min {
            get {
                return ResourceManager.GetString("flatly_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=News+Cycle:400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100% [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string journal_bootstrap_min {
            get {
                return ResourceManager.GetString("journal_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,400italic&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2017 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lumen_bootstrap_min {
            get {
                return ResourceManager.GetString("lumen_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2017 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string paper_bootstrap_min {
            get {
                return ResourceManager.GetString("paper_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Raleway:400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string readable_bootstrap_min {
            get {
                return ResourceManager.GetString("readable_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Roboto:400,500,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100% [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sandstone_bootstrap_min {
            get {
                return ResourceManager.GetString("sandstone_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Open+Sans:400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string simplex_bootstrap_min {
            get {
                return ResourceManager.GetString("simplex_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcapt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slate_bootstrap_min {
            get {
                return ResourceManager.GetString("slate_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2017 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string solar_bootstrap_min {
            get {
                return ResourceManager.GetString("solar_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spacelab_bootstrap_min {
            get {
                return ResourceManager.GetString("spacelab_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Lato:300,400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2017 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string superhero_bootstrap_min {
            get {
                return ResourceManager.GetString("superhero_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Ubuntu:400,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:sans-serif;-ms-text-size-adjust:100%;-we [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string united_bootstrap_min {
            get {
                return ResourceManager.GetString("united_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootswatch v4.0.0
        /// * Homepage: https://bootswatch.com
        /// * Copyright 2012-2018 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */@import url(&quot;https://fonts.googleapis.com/css?family=Roboto:400,700&quot;);:root{--blue:#2A9FD6;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#CC0000;-- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v4_cyborg_bootstrap_min {
            get {
                return ResourceManager.GetString("v4_cyborg_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootswatch v4.0.0
        /// * Homepage: https://bootswatch.com
        /// * Copyright 2012-2018 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */@import url(&quot;https://fonts.googleapis.com/css?family=Raleway:400,700&quot;);:root{--blue:#4582EC;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#d9534f;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v4_litera_bootstrap_min {
            get {
                return ResourceManager.GetString("v4_litera_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootswatch v4.0.0
        /// * Homepage: https://bootswatch.com
        /// * Copyright 2012-2018 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */@import url(&quot;https://fonts.googleapis.com/css?family=Nunito+Sans:400,600&quot;);:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#d953 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v4_lux_bootstrap_min {
            get {
                return ResourceManager.GetString("v4_lux_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootswatch v4.0.0
        /// * Homepage: https://bootswatch.com
        /// * Copyright 2012-2018 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */@import url(&quot;https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&quot;);:root{--blue:#2196F3;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v4_materia_bootstrap_min {
            get {
                return ResourceManager.GetString("v4_materia_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootswatch v4.0.0
        /// * Homepage: https://bootswatch.com
        /// * Copyright 2012-2018 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */@import url(&quot;https://fonts.googleapis.com/css?family=Montserrat&quot;);:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#FF7851;--oran [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v4_minty_bootstrap_min {
            get {
                return ResourceManager.GetString("v4_minty_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootswatch v4.0.0
        /// * Homepage: https://bootswatch.com
        /// * Copyright 2012-2018 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */:root{--blue:#007bff;--indigo:#6610f2;--purple:#593196;--pink:#e83e8c;--red:#FC3939;--orange:#fd7e14;--yellow:#EFA31D;--green:#13B955;--teal:#20c997;--cyan: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v4_pulse_bootstrap_min {
            get {
                return ResourceManager.GetString("v4_pulse_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootswatch v4.0.0
        /// * Homepage: https://bootswatch.com
        /// * Copyright 2012-2018 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v4.0.0 (https://getbootstrap.com)
        /// * Copyright 2011-2018 The Bootstrap Authors
        /// * Copyright 2011-2018 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */@import url(&quot;https://fonts.googleapis.com/css?family=Neucha|Cabin+Sketch&quot;);:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc35 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v4_sketchy_bootstrap_min {
            get {
                return ResourceManager.GetString("v4_sketchy_bootstrap_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&quot;https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,700&quot;);/*!
        /// * bootswatch v3.3.7
        /// * Homepage: http://bootswatch.com
        /// * Copyright 2012-2016 Thomas Park
        /// * Licensed under MIT
        /// * Based on Bootstrap
        ///*//*!
        /// * Bootstrap v3.3.7 (http://getbootstrap.com)
        /// * Copyright 2011-2016 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */html{font-family:san [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string yeti_bootstrap_min {
            get {
                return ResourceManager.GetString("yeti_bootstrap_min", resourceCulture);
            }
        }
    }
}
